language: php

php:
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

script: vendor/bin/phpunit --testsuite unit
