name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: [7.4]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        tools: composer

    - name: Install dependencies
      run: composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

    - name: Run tests
      run: vendor/bin/phpunit --testsuite unit