name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch: # Added trigger for manual execution

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: [7.4]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        tools: composer

    - name: Install dependencies
      run: composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse

    - name: Run Rector
      id: rector
      run: vendor/bin/rector process

    - name: Commit Rector changes if any
      if: steps.rector.outcome == 'success' && steps.rector.outputs.changes == 'true'
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Apply Rector changes"

    - name: Create .env file
      run: |
        echo "SOFT_SWITCH_API_URL=" >> .env
        echo "SOFT_SWITCH_API_USERNAME=" >> .env
        echo "SOFT_SWITCH_API_KEY=" >> .env

    - name: Run tests
      run: vendor/bin/phpunit --testsuite unit